### ISSUE TITLE
Missed account-scope datasets

### ISSUE THREAD

**Issue by m0ps** [coralogix/terraform-coralogix-cloudflare#6]
The support for the following account-scoped log datasets is missing in the module:
              "access_requests",
              "casb_findings",
              "device_posture_results",
              "dns_firewall_logs",
              "magic_ids_detections",
              "workers_trace_events",
              "zero_trust_network_sessions"
              
https://developers.cloudflare.com/logs/reference/log-fields/account/
https://github.com/coralogix/terraform-coralogix-cloudflare/blob/master/modules/logpush-job/variables.tf#L21

**Comment by royfur** [comment]
The missing datasets are now added
